image: gradle:jdk11

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
    paths:
        - .gradle/wrapper
        - .gradle/caches

stages:
    - build
    - test
    - visualize
    - deploy

package:
    stage: build
    script:
        - gradle shadowJar
    artifacts:
        paths:
            - build/libs/*.jar
        expire_in: 1 week

test:
    stage: test
    script:
        - gradle test jacocoTestReport printCoverage
    needs: ["package"]
    dependencies:
        - package
    artifacts:
        when: always
        paths:
            - build/reports/jacoco/test/**
            - build/reports/tests/test/**
        reports:
            junit: build/test-results/test/**/TEST-*.xml

coverage:
    stage: visualize
    image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
    script:
        # convert report from jacoco to cobertura, using relative project path
        - python /opt/cover2cover.py build/reports/jacoco/test/jacocoTestReport.xml $CI_PROJECT_DIR/src/main/java/ > build/reports/cobertura.xml
    needs: ["test"]
    dependencies:
        - test
    artifacts:
        reports:
            cobertura: build/reports/cobertura.xml

deploy_production:
    stage: deploy
    environment: production
    needs: ["coverage", "package"]
    dependencies:
        - coverage
        - package
    script:
        - apt update
        - apt -y install rsync ssh
        - chmod 600 $KEY
        - ssh -i $KEY -p $PORT -o StrictHostKeyChecking=no discord@$IP 'echo test' &> /dev/null # prevent dumping IP on next command
        - rsync -Pav -e "ssh -i $KEY -p $PORT -o StrictHostKeyChecking=no" build/libs/io.banditoz.mchelper-all.jar discord@$IP:/opt/mchelper/io.banditoz.mchelper-all.jar
        - ssh -i $KEY -p $PORT -o StrictHostKeyChecking=no discord@$IP 'sudo /bin/systemctl restart mchelper.service'
    only:
        - master

new_commands:
    stage: deploy
    needs: ["coverage"]
    dependencies:
        - coverage
    script:
        - cp -v COMMANDS.md COMMANDS_OLD.md
        - echo "$PRIVATE_TOKEN" > token
        - apt update
        - apt -y install curl
        - gradle run --args="dumpcommands"
        - bash push_commands_to_gitlab.sh
    only:
        - master
