image: registry.gitlab.com/heybanditoz/mchelper-build-image:java21-postgres16
before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle_home

cache:
    paths:
        - .gradle
        - .gradle_home
        - build

stages:
    - build
    - test
    - visualize
    - deploy

package:
    stage: build
    script:
        - ./gradlew shadowJar --no-daemon
    artifacts:
        paths:
            - build/libs/*.jar
        expire_in: 1 week

test:
    stage: test
    script:
        - rc-service postgresql start
        # We love bash so much, this looks crazy, but you're just gonna have to trust me.
        - su -c "psql --command 'ALTER USER postgres WITH PASSWORD \$\$postgres\$\$;'" postgres
        - ln -s src/main/resources/sql sql
        # Run tests!
        # DatabaseInitializationTests runs the migrations for us.
        - DB="postgres" HOST="127.0.0.1" USER="postgres" PASS="postgres" SCHEMA="public" ./gradlew test jacocoTestReport --no-daemon
    needs: ["package"]
    dependencies:
        - package
    coverage: '/    - Instruction Coverage: ([0-9.]+)%/'
    artifacts:
        when: always
        paths:
            - build/reports/jacoco/test/**
            - build/reports/tests/test/**
        reports:
            junit: build/test-results/test/**/TEST-*.xml
            coverage_report:
                coverage_format: jacoco
                path: build/reports/jacoco/test/jacocoTestReport.xml

create_image:
    stage: deploy
    image: docker:28.4.0-dind
    cache: []
    services:
        - docker:28.4.0-dind
    variables:
        IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker pull $IMAGE_TAG || true
        - docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $IMAGE_TAG -t $IMAGE_TAG .
        - docker push $IMAGE_TAG

#new_commands:
#    stage: deploy
#    needs: ["coverage"]
#    dependencies:
#        - coverage
#    script:
#        - cp -v COMMANDS.md COMMANDS_OLD.md
#        - echo "$PRIVATE_TOKEN" > token
#        - apt update
#        - apt -y install curl
#        - DB="postgres" HOST="127.0.0.1" USER="postgres" PASS="postgres" SCHEMA="public" gradle run --args="dumpcommands"
#        - bash push_commands_to_gitlab.sh
#    only:
#        - master
