image: gradle:jdk17

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
    paths:
        - .gradle/wrapper
        - .gradle/caches

stages:
    - build
    - test
    - visualize
    - deploy

package:
    stage: build
    script:
        - gradle shadowJar
    artifacts:
        paths:
            - build/libs/*.jar
        expire_in: 1 week

test:
    stage: test
    script:
        - apt-get update
        - apt-get -y install mariadb-server
        - service mysql start
        - mysql -uroot --password="" -e "CREATE DATABASE test COLLATE utf8mb4_general_ci" # don't prompt for password
        - mysql -uroot --password="" -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'pass'"
        - DB="test" HOST="127.0.0.1:3306" USER="root" PASS="pass" gradle test jacocoTestReport printCoverage
    needs: ["package"]
    dependencies:
        - package
    artifacts:
        when: always
        paths:
            - build/reports/jacoco/test/**
            - build/reports/tests/test/**
        reports:
            junit: build/test-results/test/**/TEST-*.xml

coverage:
    stage: visualize
    image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
    script:
        # convert report from jacoco to cobertura, using relative project path
        - python /opt/cover2cover.py build/reports/jacoco/test/jacocoTestReport.xml $CI_PROJECT_DIR/src/main/java/ > build/reports/cobertura.xml
    needs: ["test"]
    dependencies:
        - test
    artifacts:
        reports:
            cobertura: build/reports/cobertura.xml

create_image:
    stage: deploy
    image: docker:19.03.13
    services:
        - docker:19.03.12-dind
    variables:
        IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    needs: ["coverage", "package"]
    dependencies:
        - coverage
        - package
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -t $IMAGE_TAG .
        - docker push $IMAGE_TAG
    only:
        - master

new_commands:
    stage: deploy
    needs: ["coverage"]
    dependencies:
        - coverage
    script:
        - cp -v COMMANDS.md COMMANDS_OLD.md
        - echo "$PRIVATE_TOKEN" > token
        - apt update
        - apt -y install curl
        - DB="test" HOST="127.0.0.1:3306" USER="root" PASS="root" gradle run --args="dumpcommands"
        - bash push_commands_to_gitlab.sh
    only:
        - master
