image: gradle

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

package:
  stage: build
  script:
    - gradle shadowJar
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

