image: gradle:jdk11

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
    paths:
        - .gradle/wrapper
        - .gradle/caches

package:
    stage: build
    script:
        - gradle shadowJar
    artifacts:
        paths:
            - build/libs/*.jar
        expire_in: 1 week

test:
    stage: test
    script:
        - gradle test

deploy_production:
    stage: deploy
    environment: production
    script:
        - apt update
        - apt -y install rsync ssh
        - chmod 600 $KEY
        - ssh -i $KEY -p $PORT -o StrictHostKeyChecking=no discord@$IP 'echo test' &> /dev/null # prevent dumping IP on next command
        - rsync -Pav -e "ssh -i $KEY -p $PORT -o StrictHostKeyChecking=no" build/libs/io.banditoz.mchelper-all.jar discord@$IP:/opt/mchelper/io.banditoz.mchelper-all.jar
        - ssh -i $KEY -p $PORT -o StrictHostKeyChecking=no discord@$IP 'sudo /bin/systemctl restart mchelper.service'
    only:
        - master
