---
version: '3.3'
services:
    mchelper:
        container_name: mchelper
        volumes:
            - './application.yml:/app/application.yml'
        environment:
            - TZ=America/Denver  # swap this for your timezone, affects logging and dates in SQL
        image: registry.gitlab.com/heybanditoz/mchelper:master
        deploy:
            resources:
              limits:
                  memory: 128M
        entrypoint: [ 'java', '-jar', '/app/bot.jar' ]

    postgres:
        container_name: postgres
        environment:
            - TZ=America/Denver
            - POSTGRES_PASSWORD=SuperSecret
        image: postgres:16.10-alpine
